import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useFormContext } from 'react-hook-form';
import { Download, X } from 'lucide-react';
import { toast } from '@/utils/app-toast';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { CoverImagePicker } from '@/components/CoverImagePicker';
export function MediaStep({ isSubmitting, coverMode, setCoverMode, currentImage, error, handleFileUpload, }) {
    const { setValue, watch } = useFormContext();
    const title = watch('title');
    return (_jsxs("div", { className: "space-y-6", children: [_jsx("div", { className: "flex flex-col h-full", children: _jsxs(Tabs, { value: coverMode, onValueChange: (v) => setCoverMode(v), className: "w-full flex-1 flex flex-col", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx(Label, { className: "text-base font-medium", children: "\u041E\u0431\u043B\u043E\u0436\u043A\u0430" }), _jsxs(TabsList, { className: "grid w-[300px] grid-cols-2", children: [_jsx(TabsTrigger, { value: "file", className: "cursor-pointer", children: "\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044C" }), _jsx(TabsTrigger, { value: "search", className: "cursor-pointer", children: "\u041F\u043E\u0438\u0441\u043A" })] })] }), _jsxs("div", { className: "flex-1 min-h-0", children: [_jsxs(TabsContent, { value: "file", className: "mt-0 space-y-6", children: [_jsxs("div", { className: "flex flex-col items-center justify-center border-2 border-dashed rounded-lg p-10 hover:bg-muted/50 transition-colors cursor-pointer relative", children: [_jsx(Input, { type: "file", accept: "image/*", onChange: handleFileUpload, disabled: isSubmitting, className: "absolute inset-0 w-full h-full opacity-0 cursor-pointer" }), _jsxs("div", { className: "text-center space-y-2", children: [_jsx("div", { className: "bg-primary/10 p-4 rounded-full inline-flex mb-2", children: _jsx(Download, { className: "h-8 w-8 text-primary" }) }), _jsx("p", { className: "font-medium", children: "\u041D\u0430\u0436\u043C\u0438\u0442\u0435 \u0434\u043B\u044F \u0432\u044B\u0431\u043E\u0440\u0430 \u0444\u0430\u0439\u043B\u0430" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "PNG, JPG, WEBP (\u041C\u0430\u043A\u0441 5MB)" })] })] }), currentImage && (_jsx("div", { className: "flex justify-center animate-in fade-in zoom-in-95 duration-200", children: _jsxs("div", { className: "relative w-[180px] aspect-[2/3] rounded-lg overflow-hidden shadow-md border group", children: [_jsx("img", { src: currentImage, alt: "Preview", className: "w-full h-full object-cover" }), _jsx(Button, { variant: "destructive", size: "icon", className: "absolute top-2 right-2 h-8 w-8 shadow-sm opacity-0 group-hover:opacity-100 transition-opacity", onClick: () => setValue('image', ''), children: _jsx(X, { className: "h-4 w-4" }) })] }) }))] }), _jsx(TabsContent, { value: "search", className: "mt-0 h-full flex flex-col", children: _jsx(CoverImagePicker, { initialQuery: title ? `Обложка ${title}` : '', onSelect: (base64) => {
                                            setValue('image', base64);
                                            setCoverMode('file');
                                            toast.success('Обложка выбрана!');
                                        }, className: "flex-1" }) })] })] }) }), error && (_jsx("div", { className: "p-3 rounded-lg bg-destructive/10 text-destructive text-sm", children: error }))] }));
}
