import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useRef } from 'react';
import { Image as ImageIcon, Maximize2, Play, Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
export function MediaGallery({ media, onUpload, onDeleteFile, onOpenLightbox, }) {
    const fileInputRef = useRef(null);
    const handleFileChange = (e) => {
        const file = e.target.files?.[0];
        if (file)
            onUpload(file);
    };
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("h2", { className: "text-lg font-semibold flex items-center gap-2 select-none", children: [_jsx(ImageIcon, { className: "h-5 w-5 text-primary" }), "\u0413\u0430\u043B\u0435\u0440\u0435\u044F", media.files && media.files.length > 0 && (_jsxs("span", { className: "text-muted-foreground font-normal text-sm", children: ["(", media.files.length, ")"] }))] }), _jsx(Input, { type: "file", accept: "image/*,video/*", className: "hidden", ref: fileInputRef, onChange: handleFileChange }), !media.files || media.files.length === 0 ? (_jsxs("div", { className: "rounded-xl border-2 border-dashed border-muted hover:border-primary/40 transition-colors py-12 flex flex-col items-center justify-center text-center cursor-pointer", onClick: () => fileInputRef.current?.click(), children: [_jsx("div", { className: "p-3 rounded-full bg-muted mb-3", children: _jsx(Plus, { className: "h-6 w-6 text-muted-foreground" }) }), _jsx("p", { className: "font-medium text-foreground mb-1 select-none", children: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043C\u0435\u0434\u0438\u0430" }), _jsx("p", { className: "text-sm text-muted-foreground select-none", children: "\u0421\u043A\u0440\u0438\u043D\u0448\u043E\u0442\u044B, \u0430\u0440\u0442\u044B \u0438\u043B\u0438 \u0432\u0438\u0434\u0435\u043E" })] })) : (_jsxs("div", { className: "grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3", children: [media.files.map((file, index) => (_jsxs("div", { className: "group relative aspect-square rounded-lg overflow-hidden bg-muted cursor-pointer ring-1 ring-border/50 hover:ring-primary/50 transition-all", onClick: () => onOpenLightbox(media.image ? index + 1 : index), children: [file.type === 'video' ? (_jsxs("div", { className: "relative w-full h-full", children: [_jsx("video", { src: file.url, className: "w-full h-full object-cover" }), _jsx("div", { className: "absolute inset-0 flex items-center justify-center bg-black/30", children: _jsx("div", { className: "p-2 rounded-full bg-white/90", children: _jsx(Play, { className: "h-4 w-4 text-black fill-black" }) }) })] })) : (_jsx("img", { src: file.url, alt: "", className: "w-full h-full object-cover transition-transform duration-150 group-hover:scale-105", draggable: false })), _jsxs("div", { className: "absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity duration-150 flex items-center justify-center gap-2", children: [_jsx(Button, { size: "icon", variant: "secondary", className: "h-8 w-8 rounded-full cursor-pointer", children: _jsx(Maximize2, { className: "h-4 w-4" }) }), _jsx(Button, { size: "icon", variant: "destructive", className: "h-8 w-8 rounded-full cursor-pointer", onClick: (e) => {
                                            e.stopPropagation();
                                            onDeleteFile(file.id);
                                        }, children: _jsx(Trash2, { className: "h-4 w-4" }) })] })] }, file.id))), _jsxs("div", { className: "aspect-square rounded-lg border-2 border-dashed border-muted hover:border-primary/40 transition-colors flex flex-col items-center justify-center cursor-pointer", onClick: () => fileInputRef.current?.click(), children: [_jsx(Plus, { className: "h-6 w-6 text-muted-foreground" }), _jsx("span", { className: "text-xs text-muted-foreground mt-1 select-none", children: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C" })] })] }))] }));
}
