import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { X, ZoomIn, ZoomOut, RotateCcw, Download, } from 'lucide-react';
import { MIN_ZOOM, MAX_ZOOM } from './usePhotoViewerControls';
const toolbarVariants = {
    hidden: { opacity: 0, y: -20 },
    visible: { opacity: 1, y: 0, transition: { delay: 0.1, duration: 0.3 } },
};
export function PhotoViewerToolbar({ currentIndex, totalFiles, zoom, onZoomIn, onZoomOut, onResetZoom, onDownload, onClose, }) {
    return (_jsxs(motion.div, { variants: toolbarVariants, className: "absolute top-4 left-1/2 -translate-x-1/2 z-50 flex items-center gap-2 px-2 py-1.5 bg-background/95 backdrop-blur-md border border-border/50 rounded-2xl shadow-2xl", children: [_jsx(Badge, { variant: "secondary", className: "px-3 py-1 text-sm font-medium bg-primary/10 text-primary border-0", children: currentIndex !== null && `${currentIndex + 1} / ${totalFiles}` }), _jsx("div", { className: "w-px h-6 bg-border/50" }), _jsxs("div", { className: "flex items-center gap-0.5 px-1", children: [_jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 rounded-xl hover:bg-primary/10", onClick: onZoomOut, disabled: zoom <= MIN_ZOOM, children: _jsx(ZoomOut, { className: "h-4 w-4" }) }), _jsx("div", { className: "px-2 min-w-[52px] text-center", children: _jsxs("span", { className: "text-xs font-medium text-muted-foreground tabular-nums", children: [Math.round(zoom * 100), "%"] }) }), _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 rounded-xl hover:bg-primary/10", onClick: onZoomIn, disabled: zoom >= MAX_ZOOM, children: _jsx(ZoomIn, { className: "h-4 w-4" }) }), _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 rounded-xl hover:bg-primary/10", onClick: onResetZoom, disabled: zoom === 1, title: "\u0421\u0431\u0440\u043E\u0441\u0438\u0442\u044C \u043C\u0430\u0441\u0448\u0442\u0430\u0431", children: _jsx(RotateCcw, { className: "h-4 w-4" }) })] }), _jsx("div", { className: "w-px h-6 bg-border/50" }), _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 rounded-xl hover:bg-primary/10", onClick: onDownload, title: "\u0421\u043A\u0430\u0447\u0430\u0442\u044C", children: _jsx(Download, { className: "h-4 w-4" }) }), _jsx("div", { className: "w-px h-6 bg-border/50" }), _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 rounded-xl hover:bg-destructive/20 hover:text-destructive transition-colors", onClick: onClose, title: "\u0417\u0430\u043A\u0440\u044B\u0442\u044C (Esc)", children: _jsx(X, { className: "h-4 w-4" }) })] }));
}
